apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Base de données
  POSTGRES_USER: "app_user"
  POSTGRES_PASSWORD: "CHANGE_MOI_MDP_FORT_DB" # ⚠️ À changer
  POSTGRES_DB: "app_db"

  # Redis
  REDIS_PASSWORD: "CHANGE_MOI_MDP_FORT_REDIS" # ⚠️ À changer

  # JWT
  JWT_SECRET: "SUPER_SECRET_POUR_TOKENS"      # ⚠️ À changer